CUDA_VISIBLE_DEVICES=1 python -m test_model --model 'liuhaotian/llava-v1.5-7b' --data_path 'datasets' --conv-mode 'vicuna_v1'
CUDA_VISIBLE_DEVICES=1 python -m test_model --model 'liuhaotian/llava-v1.5-13b' --data_path 'datasets' --conv-mode 'vicuna_v1'
CUDA_VISIBLE_DEVICES=1 python -m test_model --model 'liuhaotian/llava-v1.6-vicuna-7b' --data_path 'datasets' --conv-mode 'vicuna_v1' 
CUDA_VISIBLE_DEVICES=1 python -m test_model --model 'liuhaotian/llava-v1.6-vicuna-13b' --data_path 'datasets' --conv-mode 'vicuna_v1' 
CUDA_VISIBLE_DEVICES=1 python -m test_model --model 'liuhaotian/llava-v1.6-34b' --data_path 'datasets' --conv-mode 'chatml_direct'
CUDA_VISIBLE_DEVICES=1 python -m test_model --model 'THUDM/cogvlm-chat-hf' --data_path 'datasets' --conv-mode 'vicuna_v1'
CUDA_VISIBLE_DEVICES=1 python -m test_model --model 'THUDM/cogvlm-grounding-generalist-hf' --data_path 'datasets' --conv-mode 'vicuna_v1'
CUDA_VISIBLE_DEVICES=1 python -m test_model --model 'THUDM/cogagent-vqa-hf' --data_path 'datasets' --conv-mode 'vicuna_v1'
CUDA_VISIBLE_DEVICES=1 python -m test_model --model '../Yi-VL-6B' --data_path 'datasets' --conv-mode 'mm_default'
CUDA_VISIBLE_DEVICES=1 python -m test_model --model '../Yi-VL-34B' --data_path 'datasets' --conv-mode 'mm_default'
CUDA_VISIBLE_DEVICES=1 python -m test_model --model 'Qwen/Qwen-VL' --data_path 'datasets' --conv-mode 'mm_default'
CUDA_VISIBLE_DEVICES=1 python -m test_model --model 'Qwen/Qwen-VL-Chat' --data_path 'datasets' --conv-mode 'mm_default'
CUDA_VISIBLE_DEVICES=1 python -m test_model --model 'internlm/internlm-xcomposer2-7b' --data_path 'datasets' --conv-mode 'mm_default'
CUDA_VISIBLE_DEVICES=1 python -m test_model --model 'internlm/internlm-xcomposer2-vl-7b' --data_path 'datasets' --conv-mode 'mm_default'
CUDA_VISIBLE_DEVICES=1 python -m test_model --model 'LanguageBind/MoE-LLaVA-Phi2-2.7B-4e' --data_path 'datasets' --conv-mode 'phi'
CUDA_VISIBLE_DEVICES=1 python -m test_model --model 'LanguageBind/MoE-LLaVA-Qwen-1.8B-4e' --data_path 'datasets' --conv-mode 'qwen'
CUDA_VISIBLE_DEVICES=1 python -m test_model --model 'LanguageBind/MoE-LLaVA-StableLM-1.6B-4e' --data_path 'datasets' --conv-mode 'stablelm'
CUDA_VISIBLE_DEVICES=1 python -m test_model --model 'mtgv/MobileVLM-1.7B' --data_path 'datasets' --conv-mode 'v1'
CUDA_VISIBLE_DEVICES=1 python -m test_model --model 'mtgv/MobileVLM-3B' --data_path 'datasets' --conv-mode 'v1'
CUDA_VISIBLE_DEVICES=1 python -m test_model --model 'mtgv/MobileVLM_V2-1.7B' --data_path 'datasets' --conv-mode 'v2'
CUDA_VISIBLE_DEVICES=1 python -m test_model --model 'mtgv/MobileVLM_V2-3B' --data_path 'datasets' --conv-mode 'v2'
CUDA_VISIBLE_DEVICES=1 python -m test_model --model 'mtgv/MobileVLM_V2-7B' --data_path 'datasets' --conv-mode 'v2'
#Could be launched from special environment
CUDA_VISIBLE_DEVICES=1 python -m test_model --model 'MAGAer13/mplug-owl2-llama2-7b' --data_path 'datasets' --conv-mode 'mplug_owl2'
#Could be launched from special environment
CUDA_VISIBLE_DEVICES=1 python -m test_model --model 'echo840/Monkey' --data_path 'datasets' --conv-mode 'mm_default'
CUDA_VISIBLE_DEVICES=1 python -m test_model --model 'echo840/Monkey-Chat' --data_path 'datasets' --conv-mode 'mm_default'
